/* Реализуйте функцию exceptionExample(), которая генерирует исключение Exception. */
fun exceptionExample(){
    throw Exception("Exception")
}